### ISSUE TITLE
README discord link seems to be broken?

### ISSUE THREAD

**Issue by hangtwenty** [Goldziher/starlite#9]
It just links to the image, seemingly.

**Comment by hangtwenty** [comment]
Confirmed, it's just the image:

```markdown
![Discord](https://img.shields.io/discord/919193495116337154?color=blue&label=chat%20on%20discord&logo=discord)
```

**Comment by Goldziher** [comment]
Thanks... annoying... there is an invite link also at the bottom of the readme, but i will see how to fix this.
